# Generated by Django 4.1.13 on 2026-05-04 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0030_apartment_fnr_max_length"),
        ("users", "0006_auditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="association",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="associations.association",
            ),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("login", "Login"),
                    ("chair_changed", "Chair changed"),
                    ("cfo_changed", "CFO changed"),
                    ("association_new", "Association created"),
                    ("budget_new", "Budget created"),
                    ("owner_new", "Owner added"),
                ],
                max_length=32,
            ),
        ),
    ]
