# Generated by Django 4.1.13 on 2026-05-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0033_bankaccount_opening_balance"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_default",
            field=models.BooleanField(default=False),
        ),
    ]
