# Generated by Django 4.1.13 on 2026-07-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0040_islandsbanki_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="associationbanksettings",
            name="isb_bank_number",
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
