# Generated by Django 4.1.13 on 2026-07-23 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("associations", "0041_associationbanksettings_isb_bank_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="associationbanksettings",
            name="isb_claim_account",
        ),
    ]
